title: "Communication Rules for MedCom HL7速 FHIR速 Messaging"
logo: Medcom-logo-2015.png
description: "Communication rules for the message exchange of MedCom HL7速 FHIR速"
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
